# Generated by Django 4.2.23 on 2025-07-04 05:28

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_tag_issue_comment_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='tags',
        ),
        migrations.AddField(
            model_name='issue',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=mainapp.models.issue_upload_path),
        ),
        migrations.AddField(
            model_name='issue',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(help_text='Markdown supported'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('TRIAGED', 'Triaged'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='OPEN', max_length=15),
        ),
    ]
